### PR TITLE
Improve Halo MCC CEA WinStore validation 

### LINKED ISSUE #197: Resolve MCC (Windows Store) Verification
### Introduction

People are reporting issues with installing SPV3 when the Windows Store version of MCC is used. This issue attempts to investigate the problem and determine a solution that is:

1. Compatible with everyone's computers, including 32-bit computers;
2. Preserves the security of the verification as much as feasibly possible.

### Testing

1. [Download and extract this ZIP file](https://github.com/yumiris/HCE/files/6002599/detect.03.zip);
2. Run the Windows Store version of MCC;
3. Run the `detect.bat` file and let me know if it says that it's correctly detected the Windows Store version.

### PR DESCRIPTION
**Pull request by loudCDPman**
Resolve  #197 
-Changes:
Implement a drive check, which will find halo mcc win-store mod enable version. CAN only be done if enable mod for halo mcc is enable through the store. This is possible due to windows having a folder called "ModifiableWindowsApps".
image
Implement a console 64 program to check winstore version of halo running process. The program runs based of process id and returns a bool. The console is hidden and will run in background.
-Possible improvements
The UI could be cleaned up from me being messy with it and wording could be improved. 
Improve integrity on the console program using process id return and a check or signing the code. 
Hope it help with the issue, really looking forward to it working for all.

### CODE REVIEW

**Comment by MirisWisdom** [comment]
Ahhh this is nifty - the dedicated console program is a delicious idea. I do wonder though, would it run on 32-bit systems? You've mentioned it's a 64-bit console. If it doesn't run on 32-bit systems, we'd be going back to square 1 with the modules check (which has been removed for the sake of 32-bit compatibility)

**Comment by BinToss** [comment]
MCC seems to only have 64-bit executables.
Halo Retail and Custom Edition are only 32-bit.

Two separate Process Detects panels could work.
To make sure it doesn't throw exceptions on 32-bit clients...
```cs
public readonly Visibility isX64 = 
  Environment.Is64BitOperatingSystem ?
  Visibility.Visible : Visibility.Hidden;

```
```xaml
<StackPanel Visibility="{Binding isX64}">
  <Content>
  </Content>
</StackPanel>
```

**Comment by MirisWisdom** [comment]
Ah, what's wrong with the current detection mechanism then? Since release, it's been updated to no longer break on 32-bit. Why not proceed with settling on the current mechanism and call it a day?

**Comment by loudCDPman** [comment]
> MCC seems to only have 64-bit executables.
> Halo Retail and Custom Edition are only 32-bit.
> 
> Two separate Process Detects panels could work.
> To make sure it doesn't throw exceptions on 32-bit clients...
> 
The Process checks if the WinStore version of halo is running which can only mean that a 64 bit windows/computer is running 
``` else if (process.ProcessName == "MCC-Win64-Shipping-WinStore")```
the console will not run unless the process is active, meaning we wont hit the 32bit exception. 

> Ah, what's wrong with the current detection mechanism then? Since release, it's been updated to no longer break on 32-bit. Why not proceed with settling on the current mechanism and call it a day?

This improve on the orignal work and fixes the issue with validating Halo CEA to check for a installation on there machine. It also includes a new way to activate the winstore version using the users drive to check if the user has halo cea (halo1.dll) installed. This just adds more security to the DRM process (by using the orignal) and improve accessibility with the new way to verify the game.

**Comment by BinToss** [comment]
I finally have time to come back to this!
I'll take a look at our current method and help combine it with this if needed.

**Comment by BinToss** [comment]
I'm going to compile for Any CPU and uncheck "Prefer 32-bit" for SPV3 and HXE, then send out the binaries for some testers to test.
If all goes well...
1. We can rely on HXE for process inference and restore process module heuristics (look for halo1.dll in process's loaded modules) without dropping support for 32-bit hardware users.
2. The Verification console app could be merged into the [existing verification system in HXE](https://github.com/HaloSPV3/HCE/blob/master/hxe/kernel/src/Process.cs) (See file history for process module heuristics).

**Comment by BinToss** [comment]
All's good for 32-bit users.
However, during the test, a minor issue related to the Retail and Custom Edition 'PID' registry value works on my system, but not on the tester's PC.

**Comment by loudCDPman** [comment]
Hey. Could it be due to permissions on the testers machine, if not would you be able to post the error, i might try to replica the issue, i got a old version halo retail laying around here.

**Comment by BinToss** [comment]
Strangely, on Tech's PC, Retail's PID registry entry was detected just fine, but Custom Edition's was not detected. Retail and CE activation inference use the same method which differs only by the path to the registry key ("Halo" for Retail, "Halo CE" for Custom Edition).

I'll fix this in another branch.
Before then, I'll focus on getting the Detect Process method working for both 32-bit and 64-bit users.

**Comment by BinToss** [comment]
@loudCDPman I've made a few minor changes to your branch to simplify the git-log and fixed a null reference exception. This will require a hard reset and force pushing on your part to keep the Pull Request up to date.

For future reference, try Rebasing onto the upstream branch instead of Merging. Doing so reduces git-log clutter.

For now, though...
```
git checkout origin/master
git remote add bintoss https://github.com/BinToss/HCE.git
git fetch bintoss
git reset --hard bintoss/master-loudCDPman
git push --force
```

Regarding the null reference exception, DeeperCheck() would exception if and because no processes were found that match the current Candidate e.g. no Halo.exe (Retail) processes were found.

**Comment by BinToss** [comment]
If you'd rather not alter your Pull Request, that's fine. I can merge it in and clean it up afterward.

**Comment by BinToss** [comment]
I'll merge in your work, amend it, and force-push the amended commits to the master.
This means you'll need to fetch HaloSPV3/HCE and reset your master to it to continue to stay in sync.

Either way, maintaining a neat and tidy commit history requires extra work if it isn't a point of focus during a branch's development.

Note: GitHub allows me to choose "Rebase and merge"
image

However, it cannot rebase because of the Merge commit at the head of your branch.

**Comment by BinToss** [comment]
Turns out, I can't modify your commit messages because they were merged in from a branch that isn't HaloSPV3's master.

**Pull request merged**
